### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by onuralparslan** [Eusebius1920/itmtogpx#3]
Hi
I have big itm file with many tracks and points. I tried to convert it to gpx by your tool, but it gave me the following error. Probably it is due to 32-bit limitations. Can you increase the limits? Maybe convert to 64-bit?

Error message is

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Data.Common.Int32Storage.SetCapacity(Int32 capacity)
   at System.Data.RecordManager.set_RecordCapacity(Int32 value)
   at System.Data.RecordManager.GrowRecordCapacity()
   at System.Data.RecordManager.NewRecordBase()
   at System.Data.DataTable.NewRecordFromArray(Object[] value)
   at System.Data.DataRowCollection.Add(Object[] values)
   at SQLiteWrapper.SQLiteBase.ReadNextRow(IntPtr statement, DataTable& table)
   at SQLiteWrapper.SQLiteBase.ExecuteQuery(String query)
   at ITM_To_GPX.Utils.SQLiteFile._GetWP(ArrayList WaypointInformation, GPX gpxfile) in C:\Users\dun\Downloads\itmtogpx-master\itmtogpx-master\ITM_To_GPX\SQLiteFile.cs:line 184
   at ITM_To_GPX.Utils.SQLiteFile.SQLiteToGPX(GPX gpxFile) in C:\Users\dun\Downloads\itmtogpx-master\itmtogpx-master\ITM_To_GPX\SQLiteFile.cs:line 44
   at ITM_To_GPX.WindowMain.ButtonConvert_Click(Object sender, EventArgs e) in C:\Users\dun\Downloads\itmtogpx-master\itmtogpx-master\ITM_To_GPX\WindowMain.cs:line 95
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ITM_To_GPX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/dun/Downloads/itmtogpx-master/itmtogpx-master/ITM_To_GPX/bin/Debug/ITM_To_GPX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.86.0.518
    Win32 Version: 0.86.0.518
    CodeBase: file:///C:/Users/dun/Downloads/itmtogpx-master/itmtogpx-master/ITM_To_GPX/bin/Debug/ICSharpCode.SharpZipLib.DLL
----------------------------------------
SQLiteWrapper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/dun/Downloads/itmtogpx-master/itmtogpx-master/ITM_To_GPX/bin/Debug/SQLiteWrapper.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Eusebius1920** [comment]
I need some time and more information to investigate this.

How big is the itm file? Can you provide me the file so I can test it?

**Comment by onuralparslan** [comment]
Sorry, I cannot not share the file, but the file size is 461 Mbytes.

**Comment by Eusebius1920** [comment]
I will take a look next weekend, but without an example file I can only guess what the error could be... - Unfortunately I dont have a device that creates itm-files anymore.

**Comment by Eusebius1920** [comment]
Could not reproduce the error, sorry.

Without reproducting I cannot fix it unfortunately...

**Comment by onuralparslan** [comment]
I found the problem. The 32bit SQLite library could not handle a big database. I compiled itmtogpx using x64 profile with a 64bit SQLite library. It solved the problem.

**Comment by Eusebius1920** [comment]
Wow, amazing! Can you prepare a Pull Request?

Otherwise I will take a look at it.

**Comment by onuralparslan** [comment]
Sorry, I don't know how to do it. May I send the project code to you so you can add it? How can I send it? Email? Google drive?
